blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability
    url: https://github.com/anaskalt/hello-py/blob/main/SECURITY.md
    about: Please report security vulnerabilities privately.
